### ISSUE TITLE
Block glyphs

### ISSUE THREAD

**Issue by mmacedoeu** [nuew/base65536#1]
Hey amazing work you have done but do you know why is there so many Block glyphs ?
Ex.:
`𠝷庨𣁵鏣墲𠱵𤧬䪁𢓻𧳻笅𒆴𡧔𥿁𥪻𠹇𓈾䈣扟𥃯𣕫𧓷儬𧡉奒㧡鈂铅𢄈𠦽𦬅𠜝𦀂𡗧𦎆栥𣔼囐𢗆𧈜狋讆𠂣𠙓𔑿𒂑瓈㐀㰄𦂦𣔡𦤨𧀄𤫈熷𦞪ꕍ鞾𨍢𢅨䠋𤏂勔𦢨𡦂籨𣉬𧂄輏𦉷𡮺𣅎𧦸𦬓䤍蘍鋘𧏃撯𓀅㙌簾䜱ꍑ䈡垾𥫹𖥧㢇𤒙䐗竧途㢌ꈩ㐀鈉笂𠏂㙀崁𨀱𡊷驅𥽗𥩁𡮼𢶳𦿝傎㦚𢌦𣐓𣺢𔕿沄𡟝尙𣼊荦䛡𧊣𡛩首𢮏𧬾𤈋𡔜𠇒𓇠砷𔕐𤗑陶桗棵𡇶蚒𢾸𢄎𠓼𢚩搛㐀𢏬𧄹𧞹𡰟𧘭𥠢䠿𧼱挅𠗰痜䬤𣐪𤊯𥦖㔎𢑅ꅆ𓃃沵𨃯罓𦙑𤂹𥟮ꗟ𦹧䚲霠𢅌迯𦾒抓劵爙𠝷𢟻䈵𦧉橞𐚮糶𢒔摟𧚇𣝕蟿㐀𠇡𥮥𒊄𠌓𦄿𠉏𧽬𡍎檠𥎑𣉖䭼𧶳𠋪闧𖤸𢆤𥶁猐𔑱𒊭𣘛𥀠𠶴𦞈𢜲𦤣迼漢𧈖㘻𤬋𣔾䜯䄜𧇞𦗺穏𦤚蹗𨑠繬𣌾𥎔𡽕𓏀聹㐀䔻𓏍𤀞𠊬𥑻𠻗𧟟𥬛渪ꍙ𢴏広㬸𤘡𣨖䧷骻ꎌ䦫𥇻𡧸𡓨秾𠀞𠛠脌𣧳㺤䘿𥥦𧯀餳噎𡤓圿𥺷魷枋𠀭𡀛苝𔓝𦐱𠆬𠲄ꇧ歒㐀𡩼𢧄𤜪𣅗忳𢔁廜戟𨊉𢂚𣌂華柷𡹊汳蔨鸱詍葺萔骽㝃伴𤔄罛諩㷟𦃿𥟙壿𢕶𤧭𠤸𦺇𠴶𥆙輱湺𧶭𤻕𢂉㔝𨊕𥋊䧷艇勌㐀𢃘𣭒𡦕𣕶封𣎻蔑𢷃𦀥𡻞ꎲ䍉疂譎𠮃怇㩰谀緁趶潟𢒿𤗃𓌼锰𦈽㢌𤍷𡢿𧉑𦩌𧜩𣥜𧘴𥮣𠁧𣮍𣿡𤋨佴𠆸𠮵庄𧦩㹋𠫯栔㐀`

**Comment by nuew** [comment]
This is a Rust port of @qntm's original version of [base65536](https://github.com/qntm/base65536). You can find some more details of why the blocks were chosen in his [base65536gen](https://github.com/qntm/base65536gen) project and [on his blog](https://qntm.org/unicodings).

Thanks for the interest!
